### ISSUE TITLE
CI run error (test-infection): ambiguous argument 'origin/ITHUB_BASE_REF'

### ISSUE THREAD

**Issue by edudobay** [bauhausphp/service-resolver#11]
The following error happened during a test run: https://github.com/bauhausphp/service-resolver/pull/10/checks?check_run_id=2202949110#step:4:120

```
make test-infection
make[1]: Entering directory '/home/runner/work/service-resolver/service-resolver'
fatal: ambiguous argument 'origin/ITHUB_BASE_REF': unknown revision or path not in the working tree.
```

The line below might be the culprit. Maybe the variable needs to be surrounded (not sure if `$(...)` or `${...}`):

https://github.com/bauhausphp/contributor-tool/blob/b1b9eb4ecfa14d88b906800df61e9c082acdc3fa/Makefile#L47

```diff
-test-infection: githubArgs = $(if ${CI},--logger-github --git-diff-filter=A --git-diff-base=origin/$GITHUB_BASE_REF)
+test-infection: githubArgs = $(if ${CI},--logger-github --git-diff-filter=A --git-diff-base=origin/${GITHUB_BASE_REF})
```

**Comment by fefas** [comment]
This run does not show the error message: https://github.com/bauhausphp/service-resolver/pull/10/checks?check_run_id=2216522704
